/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkspaceIdRouteImport } from './routes/app.$workspaceId'
import { Route as AppDmConversationIdRouteImport } from './routes/app.dm.$conversationId'
import { Route as AppWorkspaceIdChannelIdRouteImport } from './routes/app.$workspaceId.$channelId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceIdRoute = AppWorkspaceIdRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => AppRoute,
} as any)
const AppDmConversationIdRoute = AppDmConversationIdRouteImport.update({
  id: '/dm/$conversationId',
  path: '/dm/$conversationId',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceIdChannelIdRoute = AppWorkspaceIdChannelIdRouteImport.update({
  id: '/$channelId',
  path: '/$channelId',
  getParentRoute: () => AppWorkspaceIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app/$workspaceId': typeof AppWorkspaceIdRouteWithChildren
  '/app/$workspaceId/$channelId': typeof AppWorkspaceIdChannelIdRoute
  '/app/dm/$conversationId': typeof AppDmConversationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app/$workspaceId': typeof AppWorkspaceIdRouteWithChildren
  '/app/$workspaceId/$channelId': typeof AppWorkspaceIdChannelIdRoute
  '/app/dm/$conversationId': typeof AppDmConversationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app/$workspaceId': typeof AppWorkspaceIdRouteWithChildren
  '/app/$workspaceId/$channelId': typeof AppWorkspaceIdChannelIdRoute
  '/app/dm/$conversationId': typeof AppDmConversationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/app/$workspaceId'
    | '/app/$workspaceId/$channelId'
    | '/app/dm/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/app/$workspaceId'
    | '/app/$workspaceId/$channelId'
    | '/app/dm/$conversationId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/app/$workspaceId'
    | '/app/$workspaceId/$channelId'
    | '/app/dm/$conversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$workspaceId': {
      id: '/app/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/app/$workspaceId'
      preLoaderRoute: typeof AppWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dm/$conversationId': {
      id: '/app/dm/$conversationId'
      path: '/dm/$conversationId'
      fullPath: '/app/dm/$conversationId'
      preLoaderRoute: typeof AppDmConversationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$workspaceId/$channelId': {
      id: '/app/$workspaceId/$channelId'
      path: '/$channelId'
      fullPath: '/app/$workspaceId/$channelId'
      preLoaderRoute: typeof AppWorkspaceIdChannelIdRouteImport
      parentRoute: typeof AppWorkspaceIdRoute
    }
  }
}

interface AppWorkspaceIdRouteChildren {
  AppWorkspaceIdChannelIdRoute: typeof AppWorkspaceIdChannelIdRoute
}

const AppWorkspaceIdRouteChildren: AppWorkspaceIdRouteChildren = {
  AppWorkspaceIdChannelIdRoute: AppWorkspaceIdChannelIdRoute,
}

const AppWorkspaceIdRouteWithChildren = AppWorkspaceIdRoute._addFileChildren(
  AppWorkspaceIdRouteChildren,
)

interface AppRouteChildren {
  AppWorkspaceIdRoute: typeof AppWorkspaceIdRouteWithChildren
  AppDmConversationIdRoute: typeof AppDmConversationIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppWorkspaceIdRoute: AppWorkspaceIdRouteWithChildren,
  AppDmConversationIdRoute: AppDmConversationIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
